version: '3'
services:
  learn-go:
    build: .
    ports:
      - "8080:8080"
  shell:  # TODO: remove
    image: ubuntu
    command: bash -c 'while true; do true; done'
  db:
    image: postgres:9.6.3
    ports:
      - "5432:5432"
